#!/bin/sh

OWNER="smartfinn"
REPO="sass"
NAME="$REPO"

IMAGE=$(docker images -q "$OWNER/$REPO")

if ! docker inspect --format="{{ .State.Running }}" $IMAGE 2>/dev/null; then
	docker run --rm --user=$(id -u) \
		--volume=/etc/localtime:/etc/localtime:ro \
		--volume="$PWD":/src \
		--name $NAME $IMAGE $@
fi
