#!/bin/sh

OWNER="smartfinn"
REPO="libguestfs"
NAME="$REPO"

IMAGE=$(docker images -q "$OWNER/$REPO")
CMD=$(basename "$0")

docker run --rm --privileged \
	--interactive --tty \
	--volume=/etc/localtime:/etc/localtime:ro \
	--volume=/var/lib/libvirt:/var/lib/libvirt \
	--volume=/var/run/libvirt/libvirt-sock-ro:/var/run/libvirt/libvirt-sock-ro:ro \
	--volume=/var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock:ro \
	--name $NAME $IMAGE $CMD $@
