version: '3'
services:
  flexget:
    build: .
    container_name: flexget
    image: ghcr.io/smartfinn/flexget:latest
    restart: unless-stopped
    user: "${UID:-65534}:${GID:-65534}"
    ports:
      - 3539:3539
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "$HOME/.flexget:/config"
      - /media:/media
