version: '3'
services:
  monitorrent:
    build: .
    container_name: monitorrent
    image: smartfinn/monitorrent:latest
    restart: unless-stopped
    user: "${UID:-65534}:${GID:-65534}"
    ports:
      - 6687:6687
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "$HOME/.monitorrent:/config"
