version: '3'
services:
  nginx:
    build: .
    container_name: nginx
    image: smartfinn/nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "$HOME/html:/usr/share/nginx/html:ro"
