version: "2"
services:
  nginx:
    build: .
    container_name: nginx
    image: smartfinn/nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "~/html:/usr/share/nginx/html:ro"
