version: '3'
services:
  transmission:
    build: .
    container_name: transmission
    image: ghcr.io/smartfinn/transmission:latest
    restart: unless-stopped
    user: "${UID:-65534}:${GID:-65534}"
    ports:
      - 9091:9091
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "$HOME/.transmission:/config"
      - /media:/media
