name: Build flexget image

on:
  workflow_dispatch:
    inputs:
      buildArgs:
        description: "Pass --build-arg to docker build"
        default: ""
        required: false
  schedule:
    - cron: "27 5 * * 6"
  push:
    branches:
      - master
    paths:
      - "flexget/Dockerfile"
      - ".github/workflows/docker-image-flexget.yml"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  CONTEXT_PATH: ./flexget
  IMAGE_NAME: ${{ github.repository_owner }}/flexget

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: >-
          curl -s https://pypi.org/rss/project/flexget/releases.xml |
          awk -F'[<>]'
          '/<title>[vV]?[0-9]+/ {i[n++] = $3;} END {print "TAG_VER="i[0]}'
          >> $GITHUB_ENV

      - name: Get the version from buildArgs
        if: (github.event_name == 'workflow_dispatch') && (github.event.inputs.buildArgs != '')
        id: get_version_build_args
        # NOTE: build arg *_VER[SION]= should be passed first
        run: >-
          awk -F= '/_VER(SION)?=/ {if ($2 != "" ) print "TAG_VER="$2;}'
          <<< ${{ github.event.inputs.buildArgs }} >> $GITHUB_ENV

      # Build and push Docker images with Buildx
      # https://github.com/docker/build-push-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,priority=900,pattern=v{{major}},value=${{ env.TAG_VER }}
            type=semver,priority=890,pattern={{major}}.{{minor}},value=${{ env.TAG_VER }}
            type=semver,priority=880,pattern={{version}},value=${{ env.TAG_VER }}
            type=schedule,priority=700,pattern={{date 'YYYYMMDD'}}
            type=ref,priority=600,event=branch,enable=${{ github.event_name == 'push' }}
          flavor: latest=true

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.CONTEXT_PATH }}
          build-args: ${{ github.event.inputs.buildArgs }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
